#
# Automated Remediation with Dynatrace
# for hosts with high memory utilization
#
---
- name: 'Dynatrace Remediation of High Memory Utilization'
  #hosts: '{{ tags | select("search","ProcessHost") | list | replace("ProcessHost:","") }}'
  hosts: localhost
  gather_facts: yes
  vars:
    active_list: []
    provider:
      user: '{{ ansible_env.ANSIBLE_NET_USERNAME }}'
      password: '{{ ansible_env.ANSIBLE_NET_PASSWORD }}'
      server: '{{ f5_server_ip }}'
      validate_certs: no
      server_port: 443
 tasks:


# required: ensure only one entity is part of problem otherwise fail
  - name: check impacted entities object length
    include_tasks: './tasks/failure_alert.yml'
    when: "{{ impactedEntities|length > 1 }}"
          
